CREATE TABLE [USERS] (
  [USER_ID] int IDENTITY (1,1) NOT NULL
, [FIO] nchar(100) NOT NULL
, [LOGIN] nvarchar(100) NOT NULL
, [PASSWORD] nvarchar(100) NOT NULL
);
GO
ALTER TABLE [USERS] ADD CONSTRAINT [PK_USERS] PRIMARY KEY ([USER_ID]);
GO
CREATE TABLE [TAGS] (
  [TAG_ID] int IDENTITY (1,1) NOT NULL
, [USER_ID] int NOT NULL
, [NAME] nvarchar(100) NOT NULL
);
GO
ALTER TABLE [TAGS] ADD CONSTRAINT [PK_TAGS] PRIMARY KEY ([TAG_ID]);
GO